name = "ConvolutionalOperatorLearning"
uuid = "3c17ac3d-2343-4d75-b01f-81723beeda4b"
authors = ["David Hong <dahong@umich.edu>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
FFTW = "1.0.1"
ImageFiltering = "0.6.5"
OffsetArrays = "0.11.1"
julia = "1.1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
